namespace JobTracker.Core.Enums;

/// <summary>
/// Specifies the nature of an event in the application timeline.
/// </summary>
public enum TimelineEventType
{
    /// <summary>A simple textual note or remark.</summary>
    Note,
    /// <summary>A change in the application status (e.g. Applied -> Interviewing).</summary>
    StatusChange,
    /// <summary>Correspondence via e-mail.</summary>
    Email,
    /// <summary>A scheduled or completed phone call.</summary>
    PhoneCall,
    /// <summary>A formal interview (technical, behavioral, etc.).</summary>
    Interview,
    /// <summary>A technical assessment or home assignment.</summary>
    TechnicalTask,
    /// <summary>Feedback or insights generated by the AI.</summary>
    AiAnalysis,
    /// <summary>An official offer received from the employer.</summary>
    OfferReceived,
    /// <summary>An official rejection notification.</summary>
    Rejection
}