using JobTracker.Core.Models;

namespace JobTracker.Core.Interfaces;

/// <summary>
/// Interface for AI-powered job analysis services.
/// Implementations analyze job descriptions against resumes to provide match scores and insights.
/// </summary>
public interface IAIService
{
    /// <summary>
    /// Analyzes a job description against a resume to determine compatibility.
    /// </summary>
    /// <param name="jobDescription">The full text of the job posting</param>
    /// <param name="skillsList">The user's skills list from their profile</param>
    /// <param name="resumeText">The user's resume/CV text content</param>
    /// <returns>Analysis results including match score, gap analysis, and strategic advice</returns>
    Task<AiAnalysisResult> AnalyzeJobAsync(string jobDescription, string skillsList, string resumeText);

    /// <summary>
    /// Cleans and structures a pasted job description without requiring resume/profile context.
    /// </summary>
    Task<RefinedJobBriefResult> RefineJobBriefAsync(string jobDescription, string companyName, string position);

    /// <summary>
    /// Generates a tailored cover letter based on the job description and user's resume.
    /// </summary>
    /// <param name="jobDescription">Text content of the job requirement.</param>
    /// <param name="resumeText">Text content of the candidate's resume.</param>
    /// <param name="companyName">Name of the target company.</param>
    /// <param name="position">Title of the target position.</param>
    /// <returns>The generated cover letter text.</returns>
    Task<string> GenerateCoverLetterAsync(string jobDescription, string resumeText, string companyName, string position);

    /// <summary>
    /// Provides an optimized version of the resume tailored for a specific job description.
    /// </summary>
    Task<string> OptimizeResumeAsync(string jobDescription, string resumeText);

    /// <summary>
    /// Generates content using a system and user prompt, optionally in JSON mode.
    /// </summary>
    Task<string> GenerateContentAsync(string systemPrompt, string userPrompt, bool useJsonMode = false);
}

/// <summary>
/// Result of an AI job analysis operation.
/// Contains match score, skill gaps, and strategic recommendations.
/// </summary>
public class AiAnalysisResult
{
    /// <summary>
    /// Match percentage between 0-100 indicating resume-job compatibility
    /// </summary>
    public int MatchScore { get; set; }

    /// <summary>
    /// Detailed analysis of gaps between the resume and job requirements
    /// </summary>
    public string GapAnalysis { get; set; } = string.Empty;

    /// <summary>
    /// List of skills mentioned in the job that are missing from the resume
    /// </summary>
    public List<string> MissingSkills { get; set; } = new();

    /// <summary>
    /// Strategic advice for the applicant (tailoring tips, interview prep, etc.)
    /// </summary>
    public string StrategicAdvice { get; set; } = string.Empty;

    /// <summary>
    /// List of positive match points
    /// </summary>
    public List<string> GoodPoints { get; set; } = new();

    /// <summary>
    /// List of specific gaps identified
    /// </summary>
    public List<string> Gaps { get; set; } = new();

    /// <summary>
    /// List of actionable advice items
    /// </summary>
    public List<string> Advice { get; set; } = new();

    /// <summary>
    /// Potentially tailored resume content (if requested/available)
    /// </summary>
    public string? TailoredResume { get; set; }

    /// <summary>
    /// Potentially tailored cover letter content (if requested/available)
    /// </summary>
    public string? TailoredCoverLetter { get; set; }

    /// <summary>
    /// Structured full fit review generated by the AI.
    /// </summary>
    public FitReview? FitReview { get; set; }

    /// <summary>
    /// Whether the analysis completed successfully
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// Error message if the analysis failed
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Creates a successful analysis result.
    /// </summary>
    /// <param name="matchScore">The calculated compatibility percentage (0-100).</param>
    /// <param name="gapAnalysis">Markdown string detailing the identified skill/experience gaps.</param>
    /// <param name="missingSkills">List of concrete skills required by the job but missing from the resume.</param>
    /// <param name="strategicAdvice">Actionable advice for the candidate's application strategy.</param>
    /// <returns>A new <see cref="AiAnalysisResult"/> instance marked as successful.</returns>
    public static AiAnalysisResult CreateSuccess(int matchScore, string gapAnalysis, List<string> missingSkills, string strategicAdvice)
    {
        return new AiAnalysisResult
        {
            MatchScore = matchScore,
            GapAnalysis = gapAnalysis,
            MissingSkills = missingSkills,
            StrategicAdvice = strategicAdvice,
            Success = true
        };
    }

    /// <summary>
    /// Static factory for creating an empty success result.
    /// </summary>
    /// <returns>A new <see cref="AiAnalysisResult"/> instance marked as successful.</returns>
    public static AiAnalysisResult SuccessResult() => new() { Success = true };

    /// <summary>
    /// Creates a failed analysis result with an error message.
    /// </summary>
    /// <param name="errorMessage">Human-readable description of why the analysis failed.</param>
    /// <returns>A new <see cref="AiAnalysisResult"/> instance marked as failed.</returns>
    public static AiAnalysisResult CreateError(string errorMessage)
    {
        return new AiAnalysisResult
        {
            Success = false,
            ErrorMessage = errorMessage
        };
    }
}
